name: health_monitor_app
description: A health monitoring app.
version: 1.0.0
environment:
  sdk: '^3.7.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.0.0
  cloud_firestore: ^4.0.0
  firebase_auth: ^4.0.0
  sensors_plus: ^3.0.0
  camera: ^0.10.0
  permission_handler: ^10.0.0
  geolocator: ^9.0.0
  charts_flutter: ^0.12.0
  tflite_flutter: ^0.10.0
  cloud_functions: ^4.0.0
  connectivity_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0